name: Branch - Build & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build-lint:
    name: Build & Lint
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v1.0.13
    secrets: inherit

  test:
    name: Test
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-test-storybook.yml@v1.0.13
    secrets: inherit
