name: Branch - Build & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  build-lint:
    name: Build & Lint
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v3.1.1
    secrets: inherit
    with:
      use-vitest: true
