name: Main - Build, Test, Update Release & Publish

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  packages: write
  actions: write
  checks: write
  pull-requests: write
  id-token: write
  pages: write

jobs:
  build-lint:
    name: Build & Lint
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-checkout-setup-lint-build.yml@v5.6.0
    secrets: inherit
    with:
      use-vitest: true

  update-release:
    name: Update Release
    if: ${{ (github.ref == 'refs/heads/main') }}
    needs: [build-lint] #[build-lint, test]
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/update-release.yml@v5.6.0
    with:
      release-type: 'node'

  publish:
    name: Publish NPM Package
    needs: update-release
    if: ${{ needs.update-release.outputs.release-created }}
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-npm-package.yml@v5.6.0
    with:
      build-directory: dist
    secrets: inherit

  deploy-documentation:
    name: Deploy Documentation
    needs: update-release
    if: ${{ needs.update-release.outputs.release-created }}
    uses: ECAInternational/eca-reusable-workflows/.github/workflows/js-publish-storybook-documentation.yml@v5.6.0
