name: Build and Update Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  packages: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Prettier Check
        run: npx prettier . --check

      - name: Build
        run: npm run build

      - name: Build Storybook Docs
        run: npm run build-storybook-docs

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: storybook-static/

      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          pull-request-title-pattern: 'Release${component} ${version}'
          release-type: node
          package-name: '@ecainternational/eca-components'

      - name: Publish NPM Package
        run: |
          npx clear-package-json package.json > dist/package.json --fields "type, files, private, publishConfig"
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}

  deploy-documentation:
    needs: build
    if: ${{ needs.build.steps.release.outputs.release_created }}
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
