name: Build and Update Release

on:
  push:
    branches:
      - main

env:
  NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
  NODE_VERSION: 20

permissions:
  contents: write
  pull-requests: write
  packages: write
  pages: write
  id-token: write

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}

      - name: Prettier Check
        run: npx prettier . --check

  update-release:
    name: Update Release PR
    needs: build
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Run Release Please
        uses: google-github-actions/release-please-action@v3
        id: release
        with:
          pull-request-title-pattern: 'Release${component} ${version}'
          release-type: node
          package-name: '@ecainternational/eca-components'

  publish:
    name: Publish NPM Package
    runs-on: ubuntu-latest
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish NPM Package
        run: |
          npx clear-package-json package.json > dist/package.json --fields "type, files, private, publishConfig"
          cd dist
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  deploy-documentation:
    name: Deploy Documentation
    needs: update-release
    if: ${{ needs.update-release.outputs.release_created }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{env.NODE_VERSION}}
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies
        run: npm ci

      - name: Build Storybook Docs
        run: npm run build-storybook-docs

      - name: Fix permissions
        run: |
          chmod -c -R +rX "_site/" | while read line; do
          echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: storybook-static/

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
